train:
  _target_: src.datasets.LibrispeechDataset
  part: "train"
  data_dir: "data/datasets/ljspeech/LJSpeech-1.1"
  seed: 42
  val_size: 0.15
  max_audio_length: 20.0
  max_text_length: 200
  limit: 2
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  max_audio_length: 20.0
  max_text_length: 200
  limit: 2
  instance_transforms: ${transforms.instance_transforms.inference}
