train:
  _target_: src.datasets.LJSpeechDataset
  part: "train"
  data_dir: "/Users/a-gruzitski/Desktop/uni/HiFiGAN-vocoder/data/datasets/ljspeech"
  seed: 42
  val_size: 0.15
  max_wav_len: 8192
  target_sr: 22050
  max_audio_length: 20.0
  limit: 10
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.LJSpeechDataset
  part: "val"
  data_dir: "/Users/a-gruzitski/Desktop/uni/HiFiGAN-vocoder/data/datasets/ljspeech"
  seed: 42
  val_size: 0.15
  max_wav_len: 8192
  target_sr: 22050
  max_audio_length: 20.0
  limit: 10
  instance_transforms: ${transforms.instance_transforms.inference}
