_target_: src.model.HIFIGan
generator:
  channels: 80
  hidden: 512
  kernels_u: [16, 16, 4, 4]
  kernels_mrf: [3, 7, 11]
  dilations: [[[1, 1], [3, 1], [5, 1]],
          [[1, 1], [3, 1], [5, 1]],
          [[1, 1], [3, 1], [5, 1]]]
mpd:
  periods: [2, 3, 5, 7, 11]
  kernel: 5
  stride: 3
  channels: [1, 32, 128, 512, 1024]
msd:
  channels: [1, 128, 128, 512, 1024, 1024, 1024]
  kernels:  [15, 41, 41, 41, 41, 41, 5]
  strides:  [1, 2, 2, 4, 4, 1, 1]
  groups: [1, 4, 16, 16, 16, 16, 1]
