defaults:
  - model: hifi_gan
  - datasets: custom_text
inferencer:
  device: auto # device name or "auto"
  save_path: "infer" # any name here, can be a dataset name
  seed: 42
  from_pretrained: "models/final_model_weights.pth" # path to the pretrained model
  out_path: "outputs/texts"
